[tool.poetry]
name = "mctools"
version = "0.1.0"
description = "Toolset to simplify work with Multiconfigurational Calculations"
authors = ["Kirill Shumilov <shumilov.kirill98@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.23.5"
scipy = "^1.9.3"
pandas = "^1.5.2"
matplotlib = "^3.6.2"

[tool.poetry.dev-dependencies]
pytest = "^7.2.0"
ipython = "^8.6.0"
jupyter = "^1.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
